// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import storefrontui "github.com/fastygo/storefront/internal/site/storefrontui"

func StorefrontPage(data Page) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = storefrontui.StorefrontPage(storefrontProps(data)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func storefrontProps(data Page) storefrontui.StorefrontPageProps {
	return storefrontui.StorefrontPageProps{
		Hero:        heroProps(data.Hero),
		Categories:  categoryCards(data.Categories),
		Collections: collectionCards(data.Collections),
		Benefits:    benefitItems(data.Benefits),
		Product:     productPreview(data.Product),
		Rail:        railProps(data.Rail),
		Footer:      footerProps(data.Footer),
	}
}

func heroProps(hero Hero) storefrontui.HeroProps {
	return storefrontui.HeroProps{
		Kicker:       hero.Kicker,
		Title:        hero.Title,
		Description:  hero.Description,
		Primary:      action(hero.Primary),
		SlideCurrent: hero.SlideCurrent,
		SlideTotal:   hero.SlideTotal,
		Previous:     action(hero.Previous),
		Next:         action(hero.Next),
		Image: storefrontui.ImageRef{
			Src: storefrontui.PlaceholderHeroInterior,
			Alt: hero.Image.Alt,
		},
	}
}

func categoryCards(items []Category) []storefrontui.CategoryCard {
	out := make([]storefrontui.CategoryCard, 0, len(items))
	placeholders := []string{
		storefrontui.PlaceholderSofa,
		storefrontui.PlaceholderTable,
		storefrontui.PlaceholderLamp,
		storefrontui.PlaceholderVase,
	}
	for i, item := range items {
		out = append(out, storefrontui.CategoryCard{
			Title: item.Title,
			Count: item.Count,
			Href:  item.Href,
			Image: storefrontui.ImageRef{
				Src: placeholders[i%len(placeholders)],
				Alt: item.Image.Alt,
			},
		})
	}
	return out
}

func collectionCards(items []Collection) []storefrontui.CollectionCard {
	out := make([]storefrontui.CollectionCard, 0, len(items))
	placeholders := []string{
		storefrontui.PlaceholderChair,
		storefrontui.PlaceholderHeroInterior,
		storefrontui.PlaceholderTable,
	}
	for i, item := range items {
		out = append(out, storefrontui.CollectionCard{
			Label:       item.Label,
			Title:       item.Title,
			Description: item.Description,
			Href:        item.Href,
			Image: storefrontui.ImageRef{
				Src: placeholders[i%len(placeholders)],
				Alt: item.Image.Alt,
			},
		})
	}
	return out
}

func benefitItems(items []Benefit) []storefrontui.BenefitItem {
	out := make([]storefrontui.BenefitItem, 0, len(items))
	for _, item := range items {
		out = append(out, storefrontui.BenefitItem{
			Icon:        item.Icon,
			Title:       item.Title,
			Description: item.Description,
		})
	}
	return out
}

func productPreview(product Product) storefrontui.ProductPreview {
	return storefrontui.ProductPreview{
		Badge:          product.Badge,
		Name:           product.Name,
		Price:          product.Price,
		OldPrice:       product.OldPrice,
		Description:    product.Description,
		Gallery:        galleryImages(product.Gallery),
		MainImage:      imageRef(product.MainImage, storefrontui.PlaceholderProduct),
		ColorsLabel:    product.ColorsLabel,
		Colors:         swatchItems(product.Colors),
		SelectedColor:  product.SelectedColor,
		Quantity:       quantityProps(product.Quantity),
		AddAction:      action(product.AddAction),
		FavoriteAction: action(product.FavoriteAction),
		Details:        detailRows(product.Details),
	}
}

func railProps(rail Rail) storefrontui.RailProps {
	return storefrontui.RailProps{
		Cart:        cartSummary(rail.Cart),
		Filter:      filterPanel(rail.Filter),
		Inspiration: inspirationCard(rail.Inspiration),
		Newsletter: storefrontui.NewsletterProps{
			Title:       rail.Newsletter.Title,
			Description: rail.Newsletter.Description,
			Placeholder: rail.Newsletter.Placeholder,
			SubmitLabel: rail.Newsletter.SubmitLabel,
		},
		Socials: actions(rail.Socials),
	}
}

func cartSummary(cart Cart) storefrontui.CartSummary {
	return storefrontui.CartSummary{
		Title:          cart.Title,
		CountLabel:     cart.CountLabel,
		Items:          cartItems(cart.Items),
		TotalLabel:     cart.TotalLabel,
		Total:          cart.Total,
		CheckoutAction: action(cart.CheckoutAction),
		ViewCartAction: action(cart.ViewCartAction),
	}
}

func cartItems(items []CartItem) []storefrontui.CartItem {
	out := make([]storefrontui.CartItem, 0, len(items))
	placeholders := []string{storefrontui.PlaceholderSofa, storefrontui.PlaceholderTable}
	for i, item := range items {
		out = append(out, storefrontui.CartItem{
			Title:    item.Title,
			Subtitle: item.Subtitle,
			Price:    item.Price,
			Image:    imageRef(item.Image, placeholders[i%len(placeholders)]),
		})
	}
	return out
}

func filterPanel(filter Filter) storefrontui.FilterPanel {
	return storefrontui.FilterPanel{
		Title:         filter.Title,
		ResetLabel:    filter.ResetLabel,
		CategoryLabel: filter.CategoryLabel,
		CategoryValue: filter.CategoryValue,
		MaterialLabel: filter.MaterialLabel,
		Materials:     swatchItems(filter.Materials),
		Price: storefrontui.PriceRange{
			Label:    filter.Price.Label,
			MinLabel: filter.Price.MinLabel,
			MaxLabel: filter.Price.MaxLabel,
			Value:    filter.Price.Value,
		},
		ColorLabel:    filter.ColorLabel,
		Colors:        swatchItems(filter.Colors),
		ShowAllAction: action(filter.ShowAllAction),
	}
}

func inspirationCard(inspiration Inspiration) storefrontui.InspirationCard {
	return storefrontui.InspirationCard{
		Title:       inspiration.Title,
		Description: inspiration.Description,
		Action:      action(inspiration.Action),
		Image:       imageRef(inspiration.Image, storefrontui.PlaceholderVase),
	}
}

func footerProps(footer Footer) storefrontui.FooterProps {
	return storefrontui.FooterProps{
		BrandName: footer.BrandName,
		Copyright: footer.Copyright,
		Groups:    footerGroups(footer.Groups),
	}
}

func footerGroups(groups []FooterGroup) []storefrontui.FooterGroup {
	out := make([]storefrontui.FooterGroup, 0, len(groups))
	for _, group := range groups {
		out = append(out, storefrontui.FooterGroup{
			Title: group.Title,
			Links: actions(group.Links),
		})
	}
	return out
}

func galleryImages(images []Image) []storefrontui.ImageRef {
	out := make([]storefrontui.ImageRef, 0, len(images))
	for _, image := range images {
		out = append(out, imageRef(image, storefrontui.PlaceholderProduct))
	}
	return out
}

func imageRef(image Image, src string) storefrontui.ImageRef {
	return storefrontui.ImageRef{Src: src, Alt: image.Alt}
}

func swatchItems(items []Swatch) []storefrontui.SwatchItem {
	out := make([]storefrontui.SwatchItem, 0, len(items))
	for _, item := range items {
		out = append(out, storefrontui.SwatchItem{
			Label:    item.Label,
			Value:    item.Value,
			Class:    item.Class,
			Selected: item.Selected,
		})
	}
	return out
}

func quantityProps(quantity Quantity) storefrontui.QuantityProps {
	return storefrontui.QuantityProps{
		Label:      quantity.Label,
		Value:      quantity.Value,
		MinusLabel: quantity.MinusLabel,
		PlusLabel:  quantity.PlusLabel,
	}
}

func detailRows(rows []Detail) []storefrontui.DetailRow {
	out := make([]storefrontui.DetailRow, 0, len(rows))
	for _, row := range rows {
		out = append(out, storefrontui.DetailRow{Label: row.Label, Value: row.Value})
	}
	return out
}

func actions(items []Action) []storefrontui.Action {
	out := make([]storefrontui.Action, 0, len(items))
	for _, item := range items {
		out = append(out, action(item))
	}
	return out
}

func action(item Action) storefrontui.Action {
	return storefrontui.Action{
		Label:     item.Label,
		Href:      item.Href,
		AriaLabel: item.AriaLabel,
	}
}

var _ = templruntime.GeneratedTemplate
