// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package toggles

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"strings"

	t "github.com/a-h/templ"
	"github.com/fastygo/ui8kit/ui"
)

type LanguageToggleProps struct {
	ID               string
	Href             string
	DefaultLocale    string
	CurrentLocale    string
	CurrentLabel     string
	NextLocale       string
	NextLabel        string
	AvailableLocales []string
	EnhanceWithJS    bool
	SPATarget        string
}

type DarkModeToggleProps struct {
	ID                 string
	IconID             string
	Label              string
	SwitchToDarkLabel  string
	SwitchToLightLabel string
}

type HeaderLanguageToggleProps struct {
	Toggle LanguageToggleProps
}

func LanguageToggle(props LanguageToggleProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if strings.TrimSpace(props.CurrentLocale) != "" || strings.TrimSpace(props.CurrentLabel) != "" {
			templ_7745c5c3_Err = ui.Button(ui.ButtonProps{ID: languageToggleID(props.ID), Href: props.Href, Variant: "unstyled", Class: "ui-header-action-btn", Attrs: languageToggleAttrs(props)}, languageToggleLabel(props.CurrentLabel, props.CurrentLocale)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

func DarkModeToggle(props DarkModeToggleProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var3 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<span id=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(darkModeIconID(props.IconID))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/site/ui/elements/toggles/toggles.templ`, Line: 43, Col: 41}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"ui-theme-icon latty latty-moon\"></span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = ui.ButtonBlock(ui.ButtonProps{ID: darkModeToggleID(props.ID), Variant: "unstyled", Class: "ui-header-theme-btn", AriaLabel: darkModeToggleLabel(props.Label), Attrs: darkModeToggleAttrs(props)}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var3), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func HeaderLanguageToggle(props HeaderLanguageToggleProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"ui-header-language\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = LanguageToggle(props.Toggle).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func languageToggleID(value string) string {
	if strings.TrimSpace(value) != "" {
		return value
	}
	return "language-toggle"
}

func languageToggleAttrs(props LanguageToggleProps) t.Attributes {
	attrs := t.Attributes{
		"data-default-locale":    props.DefaultLocale,
		"data-current-locale":    props.CurrentLocale,
		"data-next-locale":       props.NextLocale,
		"data-next-label":        props.NextLabel,
		"data-available-locales": strings.Join(props.AvailableLocales, ","),
	}
	if props.EnhanceWithJS {
		attrs["data-ui8kit-spa-lang"] = "1"
		attrs["data-spa-target"] = props.SPATarget
	}
	return attrs
}

func languageToggleLabel(label, locale string) string {
	if strings.TrimSpace(label) != "" {
		return label
	}
	return strings.ToUpper(strings.TrimSpace(locale))
}

func darkModeToggleID(value string) string {
	if strings.TrimSpace(value) != "" {
		return value
	}
	return "ui8kit-theme-toggle"
}

func darkModeToggleAttrs(props DarkModeToggleProps) t.Attributes {
	return t.Attributes{
		"data-switch-to-dark-label":  darkModeSwitchToDarkLabel(props.SwitchToDarkLabel),
		"data-switch-to-light-label": darkModeSwitchToLightLabel(props.SwitchToLightLabel),
		"title":                      darkModeToggleLabel(props.Label),
		"aria-pressed":               "false",
	}
}

func darkModeIconID(value string) string {
	if strings.TrimSpace(value) != "" {
		return value
	}
	return "theme-toggle-icon"
}

func darkModeToggleLabel(value string) string {
	if strings.TrimSpace(value) != "" {
		return value
	}
	return "Toggle theme"
}

func darkModeSwitchToDarkLabel(value string) string {
	if strings.TrimSpace(value) != "" {
		return value
	}
	return "Switch to dark mode"
}

func darkModeSwitchToLightLabel(value string) string {
	if strings.TrimSpace(value) != "" {
		return value
	}
	return "Switch to light mode"
}

var _ = templruntime.GeneratedTemplate
